version: '3.7'
services:
    mirakurun:
        build:
          context: Mirakurun
          dockerfile: docker/Dockerfile
        image: chinachu/mirakurun:latest
        cap_add:
            - SYS_ADMIN
            - SYS_NICE
        ports:
            - "40772:40772"
            - "9229:9229"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./Mirakurun/config/:/app-config/
            - ./Mirakurun/data/:/app-data/
        environment:
            TZ: "Asia/Tokyo"
        devices:
            - /dev/px4video0:/dev/px4video0
            - /dev/px4video1:/dev/px4video1
            - /dev/px4video2:/dev/px4video2
            - /dev/px4video3:/dev/px4video3
            - /dev/bus/usb/001/004
        restart: always
        logging:
            driver: json-file
            options:
                max-file: "1"
                max-size: 10m

    mysql:
        image: mariadb:10.4
        volumes:
            - mysql-db:/var/lib/mysql
        environment:
            MYSQL_USER: epgstation
            MYSQL_PASSWORD: epgstation
            MYSQL_ROOT_PASSWORD: epgstation
            MYSQL_DATABASE: epgstation
            TZ: "Asia/Tokyo"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --performance-schema=false --expire_logs_days=1
        ports:
           - "3306:3306"
        restart: always
        logging:
            options:
                max-size: "10m"
                max-file: "3"

    epgstation:
        build:
            context: epgstation
            args:
                - CPUCORE=4
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /mnt/sda1/recorded:/app/recorded
            - /dev/dri:/dev/dri
            - ./epgstation/config:/app/config
            - ./epgstation/data:/app/data
            - ./epgstation/thumbnail:/app/thumbnail
            - ./epgstation/logs:/app/logs
        environment:
            TZ: "Asia/Tokyo"
        devices:
            - /dev/dri/renderD128:/dev/dri/renderD128
        depends_on:
            - mirakurun
            - mysql
        ports:
            - "8888:8888"
            - "8889:8889"
        #user: "1000:1000"
        restart: always

volumes:
    mysql-db:
        driver: local