- name: ＴＯＫＹＯ　ＭＸ
  type: GR
  channel: '16'
- name: ｔｖｋ
  type: GR
  channel: '18'
- name: フジテレビ
  type: GR
  channel: '21'
- name: ＴＢＳ
  type: GR
  channel: '22'
- name: テレビ東京
  type: GR
  channel: '23'
- name: テレビ朝日
  type: GR
  channel: '24'
- name: 日テレ
  type: GR
  channel: '25'
- name: ＮＨＫＥテレ
  type: GR
  channel: '26'
- name: ＮＨＫ総合
  type: GR
  channel: '27'
- name: テレ玉
  type: GR
  channel: '32'
- name: Ｊ：ＣＯＭチャンネル
  type: GR
  channel: '37'
- name: ＢＳ朝日１
  type: BS
  channel: BS01_0
  serviceId: 151
- name: ＢＳ朝日２
  type: BS
  channel: BS01_0
  serviceId: 152
- name: ＢＳ－ＴＢＳ
  type: BS
  channel: BS01_1
  serviceId: 161
- name: ＢＳテレ東
  type: BS
  channel: BS01_2
  serviceId: 171
- name: ＷＯＷＯＷプライム
  type: BS
  channel: BS03_0
  serviceId: 191
  isDisabled: false
- name: ＮＨＫＢＳプレミアム
  type: BS
  channel: BS03_1
  serviceId: 103
- name: ＮＨＫＢＳプレミアム
  type: BS
  channel: BS03_1
  serviceId: 104
- name: ＷＯＷＯＷライブ
  type: BS
  channel: BS05_0
  serviceId: 192
  isDisabled: false
- name: ＷＯＷＯＷシネマ
  type: BS
  channel: BS05_1
  serviceId: 193
  isDisabled: false
- name: ＢＳ１１イレブン
  type: BS
  channel: BS09_0
  serviceId: 211
- name: ＢＳスカパー！
  type: BS
  channel: BS11_1
  serviceId: 241
- name: ＢＳ日テレ
  type: BS
  channel: BS13_0
  serviceId: 141
- name: ＢＳ日テレ
  type: BS
  channel: BS13_0
  serviceId: 142
- name: ＢＳフジ・１８１
  type: BS
  channel: BS13_1
  serviceId: 181
- name: NHK BS1
  type: BS
  channel: BS15_0
  serviceId: 101
- name: NHK BS1 (Sub)
  type: BS
  channel: BS15_0
  serviceId: 102
- name: テレ朝チャンネル1
  type: CS
  channel: CS2
  serviceId: 298
  isDisabled: true
- name: テレ朝チャンネル2
  type: CS
  channel: CS2
  serviceId: 299
  isDisabled: true
- name: AT-X
  type: CS
  channel: CS16
  serviceId: 333
  isDisabled: true
- name: 日テレプラス
  type: CS
  channel: CS24
  serviceId: 300
  isDisabled: true
- name: AT-X HD
  type: SKY
  channel: ATXHD
  serviceId: 33435
  satelite: JCSAT3A
  isDisabled: true
- name: AXN HD
  type: SKY
  channel: AXNHD
  serviceId: 33418
  satelite: JCSAT4A
  isDisabled: true
- name: BS SPTV
  type: SKY
  channel: CH585
  serviceId: 33353
  satelite: JCSAT3A
  isDisabled: true
